### ISSUE TITLE
Image Auto-Size

### ISSUE THREAD

**Issue by mehmeh1z** [Legendsmith/Simple-Image-Sorter#2]
Hi!
Thank you so much for this program. It is exactly what I have been looking for lately.
I would like to know if it is possible to make a viewable picture adjust to the size of the program window?
(It's not convenient to resize it with the mouse wheel to see what's there)
Thank you in advance and hope for a quick response.
UPD:
Oh, and yes.
The picture should adjust exactly to the height of the application \ screen as soon as it appears in the application window.

**Comment by Legendsmith** [comment]
I've implemented it, the new release is imminent. Thank you again for your interest.
