### ISSUE TITLE
Right Click & Ctrl+z Issues

### ISSUE THREAD

**Issue by mehmeh1z** [Legendsmith/Simple-Image-Sorter#7]
Hi!
The right click doesn't work for some reason.
Instead of a picture, it opens a blank tab that you can't see in any way. (You can see it on the bottom bar)
P.S. There is not enough button to cancel the picture label. (Very much not convenient every time to include a hidden picture and look for there is the one that was incorrectly marked)

**Comment by mehmeh1z** [comment]
In general, I probably liked the version in which the pictures were shown one at a time.
The only thing that was missing in that version was that the program was in one window, not divided into two.
If suddenly there is a possibility to merge 2 windows into 1 in that version, I would be extremely grateful to you.

**Comment by Legendsmith** [comment]
Hello, try deleting prefs.json and opening a new session, does that make right click work again?
What do you mean about cancelling the picture label?
I'll see what I can do about a one at a time mode again.

**Comment by mehmeh1z** [comment]
After removing prefs.json, the images are no longer loaded at all. (Even when creating a new session.)
And if we talk about the rest, I meant the ability to instantly undo the image tag. I.e. here for example there is a picture, I decided to tag it to move to folder 1, but after that I changed my mind and would like to return to the tag picture in 1 click, as it was in past versions of the program. (Back button)

**Comment by Legendsmith** [comment]
Ok, I have identified the problem with images not loading at all, I shall remedy this in the next update.  I can also add a ctrl+Z function. 
I think the problem with the blank tab is that it was possible to render it out of the screen area, and that was happening due to prefs setting it there

**Comment by Legendsmith** [comment]
@mehmeh1z for now, you can use the last release that had single image mode. 1.7
https://github.com/Legendsmith/Simple-Image-Sorter/releases/tag/v1.7
