### ISSUE TITLE
Images load with a delay

### ISSUE THREAD

**Issue by mehmeh1z** [Legendsmith/Simple-Image-Sorter#8]
The pictures load with a delay when sorting and sometimes still don't fit in the screen.
Delay video:
https://files.catbox.moe/ztx88l.webm
Tested on Simple Image Sorter (Classic) v1.8.1

**Comment by Legendsmith** [comment]
If your hard drive is slow, fragmented, or full, or the image is very large then loading will be slow. I only notice it with huge image files. I could try to speed it up, maybe.
I can't replicate not fitting the screen, I've tried various sizes of screen/window size and never noticed it.

**Comment by mehmeh1z** [comment]
I tried it both on ssd or hdd.
Each of them had 60Gb+ free.
Lags still same.
And yes, the lags do not appear because of the weight of the pictures.
I overcompressed them for the test and they now weigh less than a megabyte, but the lags remain.

**Comment by mehmeh1z** [comment]
I have an idea that lags probably occur at the moment when the picture is trying to adjust to the size of the window.
And lags occur only if the picture is reduced to the size of the window, but not stretched.
For with small scale pictures lags though there are, but they are minimal.

**Comment by Legendsmith** [comment]
I see. can you send me an image that shows this behaviour? You can contact me on discord.
